workflow:
    - deploy

shared:
    image: golang
    environment:
        GOPATH: /sd/workspace

jobs:
    main:
        steps:
            - path: export PATH=$PATH:$GOPATH/bin
            - get: go get -t ./...
            - vet: go vet ./...
            - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
            - test: go test ./...
            # Ensure we can compile
            - build: go build -a -o /dev/null
            # Test cross-compiling as well
            - test-release: "curl -sL https://git.io/goreleaser | bash -s -- --snapshot"
    deploy:
        steps:
            - path: export PATH=$PATH:$GOPATH/bin
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get: go get -t ./...
            - tag: ./ci/git-tag.sh
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
